#!/usr/bin/env bash

# Unless explicitly stated otherwise all files in this repository are licensed under the Apache 2.0 License.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2020-Present Datadog, Inc.

set -e # exit immediately if a simple command exits with a non-zero status
set -u # report the usage of uninitialized variables

export NAME="datadog-cluster-agent"
export JOB_DIR="/var/vcap/jobs/${NAME}"
export LOG_DIR="/var/vcap/sys/log/${NAME}"
export RUN_DIR="/var/vcap/sys/run/${NAME}"

export PIDFILE="${RUN_DIR}/${NAME}.pid"
export DD_CLUSTER_AGENT="/var/vcap/packages/${NAME}/datadog-cluster-agent-cloudfoundry"
export AGENT_COMMAND="${DD_CLUSTER_AGENT} run -c ${JOB_DIR}/config/"

function echon_log {
  local message=${1}
  local timestamp=`date +%y:%m:%d-%H:%M:%S`
  printf "${timestamp} :: ${message}\n" | tee -a "/var/vcap/sys/log/${NAME}/${NAME}_script.log"
}

# Ensure proper permissions for the cluster agent directories
chown -R vcap:vcap "$JOB_DIR/config/"
chown -R vcap:vcap "$JOB_DIR/packages/datadog-cluster-agent/"

case ${1:-help} in
  start)
    echon_log "Starting Datadog Cluster Agent: "
    (
        {
            exec chpst -v -u vcap:vcap $AGENT_COMMAND
        } >>${LOG_DIR}/${NAME}.stdout.log \
        2>>${LOG_DIR}/${NAME}.stderr.log
    ) &
    echo $! > ${PIDFILE}
    echo "$(<${PIDFILE}). Done"
    ;;
  stop)
    echon_log "Stopping Datadog Cluster Agent: $(<${PIDFILE}). "
    kill -9 `cat $PIDFILE`
    rm -f $PIDFILE
    echon_log "Done"
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    ;;
esac
exit 0
